import {generateId} from '../generate';
import type {HttpStatusError} from '../http-status';

type ExceptionOptions = {
	name?: string;
	cause?: unknown;
	/** The HTTP status code generated by the origin server for this occurrence of the problem.*/
	status?: HttpStatusError;
	traceId?: string;
	meta?: Record<string, unknown>;
	/**
	 * A URI reference that identifies the
      problem type.  This specification encourages that, when
      dereferenced, it provide human-readable documentation for the
      problem type.
	* When
      this member is not present, its value is assumed to be
      "about:blank".
	*/
	type?: string;
	detail?: string;
	instance?: string;
	readableMessage?: string;
};

export interface Exception extends Error {
	__exception: boolean;
	traceId: string;
	status: HttpStatusError;
	timestamp: number;
	meta?: Record<string, unknown>;
	type?: string;
	detail?: string;
	instance?: string;
	readableMessage?: string;
	toJson(): string;
}

export interface ExceptionConstructor {
	new (message?: string, options?: ExceptionOptions): Exception;
	readonly prototype: Exception;
}

/**
 * Creates a custom exception class.
 *
 * @param defaultName - The default name for the exception.
 * @param properties - Default properties including message and HTTP status.
 * @returns A class that extends Error and implements the Exception interface.
 */
export const createCustomException = (
	properties: {
		defaultMessage: string;
		defaultName?: string;
		defaultStatus?: HttpStatusError;
	} = {
		defaultName: 'Exception',
		defaultMessage: 'Exception',
		defaultStatus: 500,
	},
): ExceptionConstructor => {
	return class extends Error implements Exception {
		__exception = true;
		meta: Record<string, unknown>;
		traceId: string;
		status: HttpStatusError;
		timestamp = Date.now();
		readableMessage?: string;
		instance?: string | undefined;
		detail?: string | undefined;
		type?: string | undefined;

		/**
		 * Constructor for the custom exception.
		 *
		 * @param message - The error message.
		 * @param options - Optional object containing additional error details.
		 */
		constructor(
			message: string = properties.defaultMessage,
			options?: ExceptionOptions,
		) {
			super(message);
			this.status = options?.status || properties.defaultStatus || 500;
			this.name = options?.name || properties.defaultName || 'Exception';
			this.cause = options?.cause;
			this.type = options?.type ?? 'about:blank';
			this.instance = options?.instance;
			this.detail = options?.detail;
			this.traceId = options?.traceId || generateId(8);
			this.readableMessage = options?.readableMessage;
			this.meta = Object.assign(
				{},
				options?.meta,
				(options?.cause as Exception | undefined)?.meta,
			);
			Object.setPrototypeOf(this, new.target.prototype);
		}

		toJson(): string {
			return JSON.stringify({
				message: this.message,
				name: this.name,
				status: this.status,
				timestamp: this.timestamp,
				traceId: this.traceId,
				meta: this.meta,
				type: this.type,
				detail: this.detail,
				instance: this.instance,
				readableMessage: this.readableMessage,
			});
		}
	};
};
